[project]
name = "tiss-curriculum-scraper"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "chromedriver-autoinstaller>=0.6.4",
    "pandas>=3.0.0",
    "requests>=2.32.5",
    "selenium>=4.40.0",
    "tqdm>=4.67.3",
]
